### PR TITLE
Nextjs setup

### PR DESCRIPTION
**Pull request by Cozyx213**
Initialized nextjs inside frontend directory

### CODE REVIEW

**Comment by Cozyx213** [comment]
added sample code from claude

**Comment by gael55x** [comment]
Let's put the job board component directly in the page. We don't need to wrap it up in an export function. We can put the CommunityHeader , SearchSection, JobCard, and CommunitySection in the components folder as well, so there will be better readability and decoupled components in the components folder and the app folder would just contain the pages.

**Comment by Cozyx213** [comment]
decoupled components in the components folder

**Review by Kinuseka — APPROVED** [review]
LGTM

**Review by gael55x — APPROVED** [review]
mmm kalami

**Pull request merged**
